### ISSUE TITLE
Trying to understand Umbra queries

### ISSUE THREAD

**Issue by mgree** [ldbc/ldbc_snb_bi#163]
The Umbra query for defining the `Message` materialized view has something in it I don't understand and I haven't been able to look up or test: what does `FORCEORDER` mean/do?

**Comment by szarnyasg** [comment]
cc @hbirler

**Comment by hbirler** [comment]
When doing a hash join, you build a hash table on one input and probe it with the other. In Umbra, the hash table build side is the left input and the probe side is the right input. Since building a hash table is slow, the optimizer places the smaller input to the left side and the larger input to the right. However, during a recursion, if you place the recursion input to the left side, even if the recursion input is relatively small in each iteration, you have to rebuild the hash table and probe it in every iteration. If you place a constant input to the left side, Umbra is able to only build that hash table once and reuse it for every recursion iteration. This is a difficult trade-off and Umbra was unable to make the right choice there (which might have changed with the latest versions).

Using an experimental FORCEORDER flag, we forced Umbra's optimizer to use the given order for the join (Comment on the left/hash table build side, recursion input on the right/probe side). This way, we only scan Comment once and build a hash table on it. Then, in every recursion iteration, we keep probing this same hash table with the recursion input.

Umbra's optimizer is generally great so we didn't use FORCEORDER anywhere else. I remember trying it and making the queries actually slower because my intuition was worse than Umbra's optimizer. Still, the total number of tuples that are produced within a recursion is in general extremely difficult to estimate.

**Comment by mgree** [comment]
I see... that makes sense. Thank you! (The query certainly seems to be _working_ without it, but I wanted to be sure I wasn't missing an important part of its semantics.)

Would it make sense to leave a comment to indicate that it's just an optimizer hint? Happy to file a PR (or not).

**Comment by szarnyasg** [comment]
@mgree sure, PRs are welcome. For larger PRs, you'll need a [CLA](https://ldbcouncil.org/docs/LDBC.Individual.Contributor.License.Agreement.Form-2020-10-23.pdf) but for adding comments, it's not required to sign one.
